modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="halloween_in_thousand_years"
version="1.0.0"
displayName="Halloween In 1000 Years"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Pato Salvaje, MCreator"

[[dependencies.halloween_in_thousand_years]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




